---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time={{apt_cache_timeout}}
  tags: bootstrap

- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  tags: bootstrap
  with_items:
    - zookeeper
    - zookeeperd

- name: Overwrite myid file.
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid
  tags: deploy

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  tags: deploy

# zookeeperd installs both /etc/init.d/zookeeper.conf and /etc/init/zookeeper.
# service gets confused about which one to use, so we force it to use Upstart.
- name: Restart zookeeper
  command: "service zookeeper restart"
  tags: deploy
