---
- name: Add mesosphere repo
  yum: name=http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm state=present

- name: Downloading and enable the EPEL repository definitions.
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

- name: Install os packages
  yum: name={{item}} state=present
  with_items:
    - wget
    - curl
    - unzip
    - libselinux-python 
    - python-setuptools
    - mesos-{{mesos_version}}
