---
- name: Scale EC2 virtual machines
  register: ec2
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    assign_public_ip: yes
    exact_count: "{{ n_vms }}"
    count_tag: "{{ [mesos_zookeeper, mesos_master, mesos_slave, mesos_marathon, mesos_cluster_id] | aws_tags }}"
    group: "{{ [mesos_zookeeper, mesos_master, mesos_slave, mesos_marathon, mesos_cluster_id] | aws_security_groups }}"
    zone: "{{ aws_subnet_az }}"
    region: "{{ aws_region }}"
    key_name: "{{ aws_key_name }}"
    image: "{{ ec2_image_id }}"
    instance_type: "{{ ec2_instance_type }}"
    instance_tags: "{{ [mesos_zookeeper, mesos_master, mesos_slave, mesos_marathon, mesos_cluster_id] | instance_tags }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    wait: yes
    wait_timeout: 300

- name: Wait for SSH on new EC2 machines
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances | rejectattr('state', 'equalto', 'terminated') | list }}"